import { useState, Suspense } from 'react'
import Head from 'next/head'

import AleatoryNumber from '@/components/AleatoryNumber'

import styles from '@/styles/Home.module.css'

const Loading = () => <div>Sorteando um número...</div>

export default function Home() {
  const [isLoading, setIsLoading] = useState(false)

  const handleGenerateRandomNumber = () => {
    setIsLoading(true)
  }

  return (
    <>
      <Head>
        <title>Sorteio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AleatoryNumber />
      </main>
    </>
  )
}
